#ifndef QTOPENSSL3RSA_GLOBAL_H
#define QTOPENSSL3RSA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTOPENSSL3RSA_LIBRARY)
#  define QTOPENSSL3RSA_EXPORT Q_DECL_EXPORT
#else
#  define QTOPENSSL3RSA_EXPORT Q_DECL_IMPORT
#endif

#endif // QTOPENSSL3RSA_GLOBAL_H
